const express=require("express")
const router=express.Router()
const validate_token=require("../middleware/tokenhandler")
const { createAdmin, signAdmin, logged_in, handle_application, view_applications } = require("../controllers/adminController")
const { add_Company, dislay_Companies, update_Company, delete_Company } = require("../controllers/companyController")
router.post("/createAdmin",createAdmin)
router.post("/signAdmin",signAdmin)
router.post("/logAdmin",validate_token,logged_in)
router.post("/applications",validate_token,handle_application)
router.post("/viewapps",validate_token,view_applications)
router.post("/addCompany",validate_token,add_Company)
router.post("/viewCompanies",validate_token,dislay_Companies)
router.post("/updateCompany",validate_token,update_Company)
router.post("/delCompany",validate_token,delete_Company)
module.exports=router