const express=require("express")
const router=express.Router()
const {registerStu,logged_in,signStu, updateStu, deleteStu, getStu}=require("../controllers/stuController")
const {apply_placement,affirm_student, getApplication}=require("../controllers/placementController")
const upload=require("../middleware/uploadHandler")
const validate_token=require("../middleware/tokenhandler")
router.post("/registerStu",registerStu)
router.post("/signStu",signStu)
router.post("/loginStu",validate_token,logged_in)
router.post("/updateStu",validate_token,updateStu)
router.post("/delStu",validate_token,deleteStu)
router.post("/apply",validate_token,upload,apply_placement)
router.post("/affirm",validate_token,affirm_student)
router.post('/getStu',validate_token,getStu)
router.post('/getApply',validate_token,getApplication)

module.exports=router